DROP TABLE IF EXISTS student;
  
CREATE TABLE student(
    id INT AUTO_INCREMENT  PRIMARY KEY,
    first_name VARCHAR(250) NOT NULL,
    last_name VARCHAR(250) NOT NULL,
    email VARCHAR(200) DEFAULT NULL
);